/-
Copyright (c) 2026 Kenta.
Authors: Kenta
AI usage: Developed with assistance from Claude Code (Fable 5, 1M context,
high reasoning).
-/
import Mathlib.Algebra.Group.Subgroup.Finite
import Mathlib.GroupTheory.SpecificGroups.Alternating
import FiniteSimpleGroups.Sporadic.M12.Permutations

/-!
# The generated subgroup

This file defines the experimental `M12` as the subgroup of `Equiv.Perm (Fin 12)`
generated by the three explicit permutations in `SporadicM12.Permutations`.
-/

namespace Sporadic

/-- The subgroup generated by the three degree-12 Mathieu generator candidates. -/
def M12Subgroup : Subgroup Perm12 :=
  Subgroup.closure ({m12a, m12b, m12c} : Set Perm12)

/-- The experimental Mathieu group `M12`, as a type. -/
abbrev M12 : Type :=
  M12Subgroup

instance instGroupM12 : Group M12 :=
  inferInstance

noncomputable instance instFintypeM12 : Fintype M12 := by
  classical
  infer_instance

/-- The canonical embedding of `M12` into the ambient degree-12 permutation group. -/
abbrev M12.toPerm (g : M12) : Perm12 :=
  g.1

/-- The first generator belongs to the generated subgroup. -/
theorem m12a_mem_M12Subgroup : m12a ∈ M12Subgroup :=
  Subgroup.subset_closure (by simp)

/-- The second generator belongs to the generated subgroup. -/
theorem m12b_mem_M12Subgroup : m12b ∈ M12Subgroup :=
  Subgroup.subset_closure (by simp)

/-- The third generator belongs to the generated subgroup. -/
theorem m12c_mem_M12Subgroup : m12c ∈ M12Subgroup :=
  Subgroup.subset_closure (by simp)

theorem m12a_mem_alternatingGroup : m12a ∈ alternatingGroup (Fin 12) := by
  rw [Equiv.Perm.mem_alternatingGroup]
  decide

theorem m12b_mem_alternatingGroup : m12b ∈ alternatingGroup (Fin 12) := by
  rw [Equiv.Perm.mem_alternatingGroup]
  decide

theorem m12c_mem_alternatingGroup : m12c ∈ alternatingGroup (Fin 12) := by
  rw [Equiv.Perm.mem_alternatingGroup]
  decide

/-- The generated `M12` subgroup lies inside the ambient alternating group. -/
theorem M12Subgroup_le_alternatingGroup : M12Subgroup ≤ alternatingGroup (Fin 12) := by
  rw [M12Subgroup]
  rw [Subgroup.closure_le]
  intro g hg
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg
  rcases hg with rfl | rfl | rfl
  · exact m12a_mem_alternatingGroup
  · exact m12b_mem_alternatingGroup
  · exact m12c_mem_alternatingGroup

/-- Every element of the generated `M12` subgroup is an even permutation. -/
theorem M12_toPerm_mem_alternatingGroup (g : M12) : g.1 ∈ alternatingGroup (Fin 12) :=
  M12Subgroup_le_alternatingGroup g.2

end Sporadic
