/-
Copyright (c) 2026 Kenta.
Authors: Kenta
AI usage: Developed with assistance from Claude Code (Fable 5, 1M context,
high reasoning).
-/
import Mathlib.GroupTheory.Perm.ViaEmbedding
import FiniteSimpleGroups.Sporadic.M11.Statement
import FiniteSimpleGroups.Sporadic.M12.GeneratedSubgroup

/-!
# The embedded copy of M11 inside the degree-12 permutations

The first two `M12` generators fix the twelfth point, so the subgroup they
generate is the image of the `M11` project's group under the natural
embedding `Equiv.Perm (Fin 11) →* Equiv.Perm (Fin 12)`.

This file builds that embedding and transports the two `M11` milestone
theorems (`Nat.card M11 = 7920` and `IsSimpleGroup M11`) to the embedded copy.
-/

namespace Sporadic
namespace M11Embedding

/-- `Fin 11` as the subtype of points of `Fin 12` below `11`. -/
def finElevenEquiv : Fin 11 ≃ {x : Fin 12 // x.val < 11} where
  toFun i := ⟨⟨i.val, Nat.lt_succ_of_lt i.isLt⟩, i.isLt⟩
  invFun x := ⟨x.1.val, x.2⟩
  left_inv _ := rfl
  right_inv _ := rfl

/-- The embedding of degree-11 permutations into degree-12 permutations,
fixing the twelfth point. -/
def embedPerm : Perm11 →* Perm12 :=
  Equiv.Perm.extendDomainHom finElevenEquiv

theorem embedPerm_injective : Function.Injective embedPerm :=
  Equiv.Perm.extendDomainHom_injective finElevenEquiv

set_option maxRecDepth 20000 in
/-- The embedding sends the `M11` 11-cycle generator to the `M12` one. -/
theorem embedPerm_m11a : embedPerm m11a = m12a := by
  apply Equiv.ext
  decide

set_option maxRecDepth 20000 in
/-- The embedding sends the second `M11` generator to the second `M12` one. -/
theorem embedPerm_m11b : embedPerm m11b = m12b := by
  apply Equiv.ext
  decide

/-- The embedded copy of the `M11` subgroup inside the degree-12 permutations. -/
def EmbeddedM11 : Subgroup Perm12 :=
  M11Subgroup.map embedPerm

/-- The embedded copy is generated by the first two `M12` generators. -/
theorem embeddedM11_eq_closure :
    EmbeddedM11 = Subgroup.closure ({m12a, m12b} : Set Perm12) := by
  rw [EmbeddedM11, M11Subgroup, MonoidHom.map_closure]
  congr 1
  rw [Set.image_insert_eq, Set.image_singleton, embedPerm_m11a, embedPerm_m11b]

/-- The embedded copy is isomorphic to the `M11` project's group. -/
noncomputable def embeddedM11Equiv : M11 ≃* EmbeddedM11 :=
  M11Subgroup.equivMapOfInjective embedPerm embedPerm_injective

/-- The embedded copy has the `M11` cardinality. -/
theorem card_embeddedM11 : Nat.card EmbeddedM11 = 7920 := by
  rw [← Nat.card_congr embeddedM11Equiv.toEquiv]
  exact card_M11

/-- The embedded copy is a simple group, transported from `simple_M11`. -/
theorem isSimpleGroup_embeddedM11 : IsSimpleGroup EmbeddedM11 := by
  haveI := simple_M11
  exact embeddedM11Equiv.symm.isSimpleGroup

/-- The embedded copy lies inside the `M12` subgroup. -/
theorem embeddedM11_le_M12Subgroup : EmbeddedM11 ≤ M12Subgroup := by
  rw [embeddedM11_eq_closure, Subgroup.closure_le]
  intro g hg
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg
  rcases hg with rfl | rfl
  · exact m12a_mem_M12Subgroup
  · exact m12b_mem_M12Subgroup

/-- Every element of the embedded copy fixes the twelfth point. -/
theorem fixes_eleven_of_mem_embeddedM11 {g : Perm12} (hg : g ∈ EmbeddedM11) :
    g 11 = 11 := by
  rw [embeddedM11_eq_closure] at hg
  exact Subgroup.closure_induction
    (p := fun x _ => x (11 : Fin 12) = 11)
    (fun x hx => by
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
      rcases hx with rfl | rfl
      · decide
      · decide)
    (by simp)
    (fun x y _ _ hx hy => by
      change (x * y) (11 : Fin 12) = 11
      rw [Equiv.Perm.mul_apply, hy, hx])
    (fun x _ hx => by
      change x⁻¹ (11 : Fin 12) = 11
      exact Equiv.Perm.inv_eq_iff_eq.mpr hx.symm)
    hg

end M11Embedding
end Sporadic
