#!/usr/bin/env python3
"""Generate the data-heavy Lean files for the L34 (PSL(3,4)) layer."""

import json

st = json.load(open("output/l34_data.json"))
LEAN3 = {"1": "Gen.e1", "2": "Gen.e2", "3": "Gen.e3"}
LEAN22 = {"a": "Gen.a", "A": "Gen.aInv", "b": "Gen.b", "B": "Gen.bInv"}

def word3(w):
    if not w:
        return "[]"
    return "[" + ", ".join(LEAN3[c] for c in w) + "]"

def word22(w):
    if not w:
        return "[]"
    return "[" + ", ".join(LEAN22[c] for c in w) + "]"

def match_table(tbl, fmt):
    lines = []
    for x in sorted(int(k) for k in tbl):
        lines.append(f"  | {x} => {fmt(tbl[str(x)])}")
    lines.append("  | _ => []")
    return "\n".join(lines)

def cyc_prod(cycles, n):
    parts = [f"List.formPerm ([{', '.join(map(str, c))}] : List (Fin {n}))"
             for c in cycles]
    return " *\n    ".join(parts)

# ------------------------------------------------------------- Basic.lean
gen_defs = []
for i, cyc in enumerate(st["gen_cycles"]):
    gen_defs.append(f"""/-- Elation generator {i + 1} (an involution; 8 transpositions). -/
def l34e{i + 1} : Perm21 :=
  {cyc_prod(cyc, 21)}
""")

basic = f"""/-
Copyright (c) 2026 Kenta. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenta, Claude
-/
import Mathlib.GroupTheory.Perm.Cycle.Concrete
import Mathlib.Algebra.Group.Subgroup.Finite
import Mathlib.GroupTheory.Subgroup.Simple
import SporadicM22.Basic

/-!
# L34: a concrete copy of PSL(3,4) on 21 points

Three explicit elations of PG(2,4) (computed by `scripts/gen_l34.py` and
verified there to generate a group of order 20160). Lean re-verifies all
certificate claims by `decide`.
-/

namespace Sporadic
namespace L34

/-- The ambient permutation group for the 21-point action. -/
abbrev Perm21 : Type := Equiv.Perm (Fin 21)

{chr(10).join(gen_defs)}
/-- The subgroup generated by the three elations: a copy of `PSL(3,4)`. -/
def L34Subgroup : Subgroup Perm21 :=
  Subgroup.closure ({{l34e1, l34e2, l34e3}} : Set Perm21)

instance instGroupL34 : Group L34Subgroup :=
  inferInstance

noncomputable instance instFintypeL34 : Fintype L34Subgroup := by
  classical
  infer_instance

theorem l34e1_mem : l34e1 ∈ L34Subgroup :=
  Subgroup.subset_closure (by simp)

theorem l34e2_mem : l34e2 ∈ L34Subgroup :=
  Subgroup.subset_closure (by simp)

theorem l34e3_mem : l34e3 ∈ L34Subgroup :=
  Subgroup.subset_closure (by simp)

set_option maxRecDepth 20000 in
/-- The first generator is an involution. -/
theorem l34e1_sq : l34e1 * l34e1 = 1 := by
  apply Equiv.ext
  decide

set_option maxRecDepth 20000 in
/-- The second generator is an involution. -/
theorem l34e2_sq : l34e2 * l34e2 = 1 := by
  apply Equiv.ext
  decide

set_option maxRecDepth 20000 in
/-- The third generator is an involution. -/
theorem l34e3_sq : l34e3 * l34e3 = 1 := by
  apply Equiv.ext
  decide

theorem l34e1_inv : l34e1⁻¹ = l34e1 :=
  inv_eq_of_mul_eq_one_right l34e1_sq

theorem l34e2_inv : l34e2⁻¹ = l34e2 :=
  inv_eq_of_mul_eq_one_right l34e2_sq

theorem l34e3_inv : l34e3⁻¹ = l34e3 :=
  inv_eq_of_mul_eq_one_right l34e3_sq

end L34
end Sporadic
"""
open("../SporadicM22/L34/Basic.lean", "w").write(basic)
print("wrote L34/Basic.lean")

# ------------------------------------------------------- Transitivity.lean
stab01_lines = ",\n".join(f"    {word3(w)}" for w in st["stab01_words"])

trans = f"""/-
Copyright (c) 2026 Kenta. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenta, Claude
-/
import SporadicM22.L34.Words

/-!
# Transitivity certificates for L34

Word tables for the 21-point action: the orbit of `0`, the orbit of `1`
under the stabilizer of `0`, and 48 distinct elements of the two-point
stabilizer (used for the cardinality lower bound).
-/

namespace Sporadic
namespace L34

/-- Words sending `0` to `x`. -/
def orbitZeroWord (x : Fin 21) : Word :=
  match x.val with
{match_table(st["orbit0"], word3)}

/-- Words fixing `0` and sending `1` to `x` (for `x ≠ 0`). -/
def zeroStabWord (x : Fin 21) : Word :=
  match x.val with
{match_table(st["stab0"], word3)}

set_option maxRecDepth 400000 in
/-- The first-table words send `0` to every point. -/
theorem orbitZeroWord_maps_zero_all :
    ∀ x : Fin 21, (Word.eval (orbitZeroWord x)) (0 : Fin 21) = x := by
  decide

set_option maxRecDepth 400000 in
/-- The second-table words fix `0`. -/
theorem zeroStabWord_fixes_zero_all :
    ∀ x : Fin 21, x ≠ 0 → (Word.eval (zeroStabWord x)) (0 : Fin 21) = 0 := by
  decide

set_option maxRecDepth 400000 in
/-- The second-table words send `1` to the requested nonzero point. -/
theorem zeroStabWord_maps_one_all :
    ∀ x : Fin 21, x ≠ 0 → (Word.eval (zeroStabWord x)) (1 : Fin 21) = x := by
  decide

/-- 48 candidate words for distinct elements fixing `0` and `1`. -/
def stab01WordList : List Word :=
  [
{stab01_lines}
  ]

set_option maxRecDepth 400000 in
/-- Every listed word fixes `0`. -/
theorem stab01WordList_fixes_zero :
    ∀ w ∈ stab01WordList, (Word.eval w) (0 : Fin 21) = 0 := by
  decide

set_option maxRecDepth 400000 in
/-- Every listed word fixes `1`. -/
theorem stab01WordList_fixes_one :
    ∀ w ∈ stab01WordList, (Word.eval w) (1 : Fin 21) = 1 := by
  decide

set_option maxRecDepth 1000000 in
set_option maxHeartbeats 3200000 in
-- The pairwise-distinctness certificate is intentionally checked by computation.
/-- The 48 listed words evaluate to pairwise distinct permutations. -/
theorem stab01WordList_evals_nodup :
    (stab01WordList.map Word.eval).Nodup := by
  decide

theorem stab01WordList_length : stab01WordList.length = 48 := by
  decide

end L34
end Sporadic
"""
open("../SporadicM22/L34/Transitivity.lean", "w").write(trans)
print("wrote L34/Transitivity.lean")

# ---------------------------------------------------------- Elations.lean
# elation pair data: from cycles (each elation = 8 transpositions)
def pairs_of(cycles):
    out = []
    for c in cycles:
        assert len(c) == 2
        out.append((c[0], c[1]))
    return out

el_lines = []
for x in range(21):
    for k in range(15):
        prs = pairs_of(st["elations"][str(x)][k])
        s = ", ".join(f"({a}, {b})" for a, b in prs)
        el_lines.append(f"  | {x}, {k} => [{s}]")
el_table = "\n".join(el_lines)

conj_defs = []
for i in range(3):
    rows = []
    for x in range(21):
        for k in range(15):
            rows.append(f"  | {x}, {k} => {st['conj_tables'][i][x][k]}")
    conj_defs.append(f"""/-- Conjugation index table for generator {i + 1}. -/
def conjIdx{i + 1} (x : Fin 21) (k : Fin 15) : Fin 15 :=
  match x.val, k.val with
{chr(10).join(rows)}
  | _, _ => 0
""")

el0_lines = []
for k, w in enumerate(st["elation0_words"]):
    el0_lines.append(f"  | {k} => {word3(w)}")

# commutator identity data
ci = st["comm_ids"]
comm_text = []
for i in range(3):
    (x1, k1), (x2, k2) = ci[i]
    comm_text.append(f"""set_option maxRecDepth 40000 in
/-- Generator {i + 1} as a product of four elations (a commutator). -/
theorem l34e{i + 1}_comm_id :
    l34e{i + 1} = elationAt {x1} {k1} * elationAt {x2} {k2} *
      elationAt {x1} {k1} * elationAt {x2} {k2} := by
  apply Equiv.ext
  decide +kernel

/-- The two elations witnessing the commutator identity for generator {i + 1}. -/
def commU{i + 1} : Perm21 := elationAt {x1} {k1}

def commV{i + 1} : Perm21 := elationAt {x2} {k2}

theorem commU{i + 1}_mem : commU{i + 1} ∈ L34Subgroup := elation_mem _ _

theorem commV{i + 1}_mem : commV{i + 1} ∈ L34Subgroup := elation_mem _ _

theorem commU{i + 1}_sq : commU{i + 1} * commU{i + 1} = 1 := elation_sq _ _

theorem commV{i + 1}_sq : commV{i + 1} * commV{i + 1} = 1 := elation_sq _ _
""")

elations = f"""/-
Copyright (c) 2026 Kenta. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenta, Claude
-/
import SporadicM22.L34.Transitivity

/-!
# Elations of PG(2,4) and their equivariance

For each point `x` of the 21-point plane, `elationAt x k` (`k : Fin 15`)
enumerates the fifteen nontrivial elations with center `x` — involutions
moving 16 points in eight transpositions. Certificates:

* commutativity of the fifteen elations at the base point `0`;
* conjugation tables for the three generators
  (`g * elationAt x k * g = elationAt (g x) (conjIdxI x k)`);
* membership words for the elations at `0`;
* commutator identities expressing each generator as `⁅u,v⁆` of elations.

From the tables, closure induction gives full equivariance: every element
of `L34Subgroup` permutes the elation family. This is the engine of the
Iwasawa-style simplicity proof.
-/

namespace Sporadic
namespace L34

/-- Transposition data for each elation. -/
def elationPairs (x : Fin 21) (k : Fin 15) : List (Fin 21 × Fin 21) :=
  match x.val, k.val with
{el_table}
  | _, _ => []

/-- The elation with center `x` and index `k`, as a product of swaps. -/
def elationAt (x : Fin 21) (k : Fin 15) : Perm21 :=
  ((elationPairs x k).map fun p => Equiv.swap p.1 p.2).prod

set_option maxRecDepth 200000 in
set_option maxHeartbeats 1600000 in
-- The involution certificate is intentionally checked by computation.
/-- Every elation is an involution. -/
theorem elation_sq_pointwise :
    ∀ x : Fin 21, ∀ k : Fin 15, ∀ p : Fin 21,
      (elationAt x k * elationAt x k) p = p := by
  decide +kernel

theorem elation_sq (x : Fin 21) (k : Fin 15) :
    elationAt x k * elationAt x k = 1 :=
  Equiv.ext fun p => elation_sq_pointwise x k p

theorem elation_inv (x : Fin 21) (k : Fin 15) :
    (elationAt x k)⁻¹ = elationAt x k :=
  inv_eq_of_mul_eq_one_right (elation_sq x k)

set_option maxRecDepth 200000 in
set_option maxHeartbeats 1600000 in
-- The base-point commutativity certificate is intentionally checked by computation.
/-- The fifteen elations at the base point `0` commute pairwise. -/
theorem elation_comm_zero_pointwise :
    ∀ k k' : Fin 15, ∀ p : Fin 21,
      (elationAt 0 k * elationAt 0 k') p = (elationAt 0 k' * elationAt 0 k) p := by
  decide +kernel

theorem elation_comm_zero (k k' : Fin 15) :
    elationAt 0 k * elationAt 0 k' = elationAt 0 k' * elationAt 0 k :=
  Equiv.ext fun p => elation_comm_zero_pointwise k k' p

{chr(10).join(conj_defs)}
set_option maxRecDepth 200000 in
set_option maxHeartbeats 6400000 in
-- The conjugation certificate is intentionally checked by computation.
/-- Conjugation by generator 1 permutes the elation family. -/
theorem conj1_pointwise :
    ∀ x : Fin 21, ∀ k : Fin 15, ∀ p : Fin 21,
      (l34e1 * elationAt x k * l34e1) p =
        (elationAt (l34e1 x) (conjIdx1 x k)) p := by
  decide +kernel

set_option maxRecDepth 200000 in
set_option maxHeartbeats 6400000 in
-- The conjugation certificate is intentionally checked by computation.
/-- Conjugation by generator 2 permutes the elation family. -/
theorem conj2_pointwise :
    ∀ x : Fin 21, ∀ k : Fin 15, ∀ p : Fin 21,
      (l34e2 * elationAt x k * l34e2) p =
        (elationAt (l34e2 x) (conjIdx2 x k)) p := by
  decide +kernel

set_option maxRecDepth 200000 in
set_option maxHeartbeats 6400000 in
-- The conjugation certificate is intentionally checked by computation.
/-- Conjugation by generator 3 permutes the elation family. -/
theorem conj3_pointwise :
    ∀ x : Fin 21, ∀ k : Fin 15, ∀ p : Fin 21,
      (l34e3 * elationAt x k * l34e3) p =
        (elationAt (l34e3 x) (conjIdx3 x k)) p := by
  decide +kernel

theorem conj1_eq (x : Fin 21) (k : Fin 15) :
    l34e1 * elationAt x k * l34e1⁻¹ = elationAt (l34e1 x) (conjIdx1 x k) := by
  rw [l34e1_inv]
  exact Equiv.ext fun p => conj1_pointwise x k p

theorem conj2_eq (x : Fin 21) (k : Fin 15) :
    l34e2 * elationAt x k * l34e2⁻¹ = elationAt (l34e2 x) (conjIdx2 x k) := by
  rw [l34e2_inv]
  exact Equiv.ext fun p => conj2_pointwise x k p

theorem conj3_eq (x : Fin 21) (k : Fin 15) :
    l34e3 * elationAt x k * l34e3⁻¹ = elationAt (l34e3 x) (conjIdx3 x k) := by
  rw [l34e3_inv]
  exact Equiv.ext fun p => conj3_pointwise x k p

/-- A permutation conjugates every elation to an elation at the image center. -/
def MapsElations (g : Perm21) : Prop :=
  ∀ x : Fin 21, ∀ k : Fin 15, ∃ k' : Fin 15,
    g * elationAt x k * g⁻¹ = elationAt (g x) k'

theorem mapsElations_one : MapsElations 1 := fun x k =>
  ⟨k, by simp⟩

theorem mapsElations_mul {{g h : Perm21}}
    (hg : MapsElations g) (hh : MapsElations h) : MapsElations (g * h) := by
  intro x k
  obtain ⟨k₁, hk₁⟩ := hh x k
  obtain ⟨k₂, hk₂⟩ := hg (h x) k₁
  refine ⟨k₂, ?_⟩
  have : g * h * elationAt x k * (g * h)⁻¹ =
      g * (h * elationAt x k * h⁻¹) * g⁻¹ := by
    group
  rw [this, hk₁, hk₂]
  rfl

/-- Two-sided predicate, closed under the closure operations. -/
def MapsElations₂ (g : Perm21) : Prop :=
  MapsElations g ∧ MapsElations g⁻¹

theorem mapsElations₂_gen1 : MapsElations₂ l34e1 := by
  constructor
  · exact fun x k => ⟨conjIdx1 x k, conj1_eq x k⟩
  · rw [l34e1_inv]
    exact fun x k => ⟨conjIdx1 x k, conj1_eq x k⟩

theorem mapsElations₂_gen2 : MapsElations₂ l34e2 := by
  constructor
  · exact fun x k => ⟨conjIdx2 x k, conj2_eq x k⟩
  · rw [l34e2_inv]
    exact fun x k => ⟨conjIdx2 x k, conj2_eq x k⟩

theorem mapsElations₂_gen3 : MapsElations₂ l34e3 := by
  constructor
  · exact fun x k => ⟨conjIdx3 x k, conj3_eq x k⟩
  · rw [l34e3_inv]
    exact fun x k => ⟨conjIdx3 x k, conj3_eq x k⟩

theorem mapsElations₂_one : MapsElations₂ 1 := by
  constructor
  · exact mapsElations_one
  · simpa using mapsElations_one

theorem mapsElations₂_mul {{g h : Perm21}}
    (hg : MapsElations₂ g) (hh : MapsElations₂ h) : MapsElations₂ (g * h) := by
  constructor
  · exact mapsElations_mul hg.1 hh.1
  · rw [mul_inv_rev]
    exact mapsElations_mul hh.2 hg.2

theorem mapsElations₂_inv {{g : Perm21}}
    (hg : MapsElations₂ g) : MapsElations₂ g⁻¹ := by
  constructor
  · exact hg.2
  · rw [inv_inv]
    exact hg.1

/-- Every element of `L34Subgroup` permutes the elation family (both ways). -/
theorem mapsElations₂_of_mem {{g : Perm21}} (hg : g ∈ L34Subgroup) :
    MapsElations₂ g := by
  exact Subgroup.closure_induction
    (p := fun x _ => MapsElations₂ x)
    (fun x hx => by
      simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
      rcases hx with rfl | rfl | rfl
      · exact mapsElations₂_gen1
      · exact mapsElations₂_gen2
      · exact mapsElations₂_gen3)
    mapsElations₂_one
    (fun x y _ _ hx hy => mapsElations₂_mul hx hy)
    (fun x _ hx => mapsElations₂_inv hx)
    hg

/-- Words at the base point: each elation at `0` as a generator word. -/
def elationZeroWord (k : Fin 15) : Word :=
  match k.val with
{chr(10).join(el0_lines)}
  | _ => []

set_option maxRecDepth 400000 in
set_option maxHeartbeats 3200000 in
-- The base-membership certificate is intentionally checked by computation.
/-- The base-point words evaluate to the elations at `0`. -/
theorem elationZeroWord_eval_pointwise :
    ∀ k : Fin 15, ∀ p : Fin 21,
      (Word.eval (elationZeroWord k)) p = (elationAt 0 k) p := by
  decide +kernel

theorem elationZeroWord_eval (k : Fin 15) :
    Word.eval (elationZeroWord k) = elationAt 0 k :=
  Equiv.ext fun p => elationZeroWord_eval_pointwise k p

/-- The elations at the base point belong to the group. -/
theorem elation_zero_mem (k : Fin 15) : elationAt 0 k ∈ L34Subgroup := by
  rw [← elationZeroWord_eval]
  exact Word.eval_mem_L34Subgroup _

/-- Every elation belongs to the group. -/
theorem elation_mem (x : Fin 21) (k : Fin 15) : elationAt x k ∈ L34Subgroup := by
  have hw : (Word.eval (orbitZeroWord x)) (0 : Fin 21) = x :=
    orbitZeroWord_maps_zero_all x
  set g : Perm21 := Word.eval (orbitZeroWord x) with hgdef
  have hgmem : g ∈ L34Subgroup := Word.eval_mem_L34Subgroup _
  have hginv : g⁻¹ x = 0 := by
    rw [← hw]
    exact Equiv.Perm.inv_eq_iff_eq.mpr rfl
  obtain ⟨k', hk'⟩ := (mapsElations₂_of_mem hgmem).2 x k
  rw [hginv] at hk'
  have : elationAt x k = g * elationAt 0 k' * g⁻¹ := by
    rw [← hk']
    group
  rw [this]
  exact Subgroup.mul_mem _ (Subgroup.mul_mem _ hgmem (elation_zero_mem k'))
    (Subgroup.inv_mem _ hgmem)

{chr(10).join(comm_text)}
end L34
end Sporadic
"""
open("../SporadicM22/L34/Elations.lean", "w").write(elations)
print("wrote L34/Elations.lean")

# ----------------------------------------------------------- LastPoint.lean
emb_word_defs = []
for i, w in enumerate(st["emb_words"]):
    emb_word_defs.append(f"""/-- A word certificate for the embedded generator {i + 1}. -/
def embWord{i + 1} : Word :=
  {word22(w)}
""")

last = f"""/-
Copyright (c) 2026 Kenta. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kenta, Claude
-/
import SporadicM22.Certificates.Words

/-!
# Word certificates around the last point `21`

Tables used by the simplicity proof:

* `lastOrbitWord x` sends `21` to `x` (orbit-stabilizer for the stabilizer
  of `21`);
* `lastStabWord x` fixes `21` and sends `0` to `x` (transitivity of the
  point stabilizer on the remaining 21 points);
* `embWordI` evaluates to the embedded `L34` generators (membership of the
  embedded `PSL(3,4)` in `M22`).
-/

namespace Sporadic
namespace M22Certificates
namespace LastPoint

/-- Words sending `21` to `x`. -/
def lastOrbitWord (x : Fin 22) : Word :=
  match x.val with
{match_table(st["last_orbit"], word22)}

/-- Words fixing `21` and sending `0` to `x` (for `x ≠ 21`). -/
def lastStabWord (x : Fin 22) : Word :=
  match x.val with
{match_table(st["last_stab"], word22)}

set_option maxRecDepth 400000 in
/-- The orbit words send `21` to every point. -/
theorem lastOrbitWord_maps_all :
    ∀ x : Fin 22, (Word.eval (lastOrbitWord x)) (21 : Fin 22) = x := by
  decide

set_option maxRecDepth 400000 in
/-- The stabilizer words fix `21`. -/
theorem lastStabWord_fixes_all :
    ∀ x : Fin 22, x ≠ 21 → (Word.eval (lastStabWord x)) (21 : Fin 22) = 21 := by
  decide

set_option maxRecDepth 400000 in
/-- The stabilizer words send `0` to the requested point. -/
theorem lastStabWord_maps_all :
    ∀ x : Fin 22, x ≠ 21 → (Word.eval (lastStabWord x)) (0 : Fin 22) = x := by
  decide

{chr(10).join(emb_word_defs)}
end LastPoint
end M22Certificates
end Sporadic
"""
open("../SporadicM22/Certificates/LastPoint.lean", "w").write(last)
print("wrote Certificates/LastPoint.lean")
print("done; centers =", st["centers"])
