/-
Copyright (c) 2026 Kenta.
Authors: Kenta
AI usage: Developed with assistance from OpenAI Codex and ChatGPT.
-/
import Mathlib.Algebra.Group.Subgroup.Finite
import Mathlib.GroupTheory.SpecificGroups.Alternating
import FiniteSimpleGroups.Sporadic.M11.Permutations

/-!
# The generated subgroup

This file defines the experimental `M11` as the subgroup of `Equiv.Perm (Fin 11)`
generated by the two explicit permutations in `FiniteSimpleGroups.Sporadic.M11.Permutations`.
-/

namespace Sporadic

/-- The subgroup generated by the two degree-11 Mathieu generator candidates. -/
def M11Subgroup : Subgroup Perm11 :=
  Subgroup.closure ({m11a, m11b} : Set Perm11)

/-- The experimental Mathieu group `M11`, as a type. -/
abbrev M11 : Type :=
  M11Subgroup

instance instGroupM11 : Group M11 :=
  inferInstance

noncomputable instance instFintypeM11 : Fintype M11 := by
  classical
  infer_instance

/-- The canonical embedding of `M11` into the ambient degree-11 permutation group. -/
abbrev M11.toPerm (g : M11) : Perm11 :=
  g.1

/-- The first generator belongs to the generated subgroup. -/
theorem m11a_mem_M11Subgroup : m11a ∈ M11Subgroup :=
  Subgroup.subset_closure (by simp)

/-- The second generator belongs to the generated subgroup. -/
theorem m11b_mem_M11Subgroup : m11b ∈ M11Subgroup :=
  Subgroup.subset_closure (by simp)

theorem m11a_mem_alternatingGroup : m11a ∈ alternatingGroup (Fin 11) := by
  rw [Equiv.Perm.mem_alternatingGroup]
  decide

theorem m11b_mem_alternatingGroup : m11b ∈ alternatingGroup (Fin 11) := by
  rw [Equiv.Perm.mem_alternatingGroup]
  decide

/-- The generated `M11` subgroup lies inside the ambient alternating group. -/
theorem M11Subgroup_le_alternatingGroup : M11Subgroup ≤ alternatingGroup (Fin 11) := by
  rw [M11Subgroup]
  rw [Subgroup.closure_le]
  intro g hg
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg
  rcases hg with rfl | rfl
  · exact m11a_mem_alternatingGroup
  · exact m11b_mem_alternatingGroup

/-- Every element of the generated `M11` subgroup is an even permutation. -/
theorem M11_toPerm_mem_alternatingGroup (g : M11) : g.1 ∈ alternatingGroup (Fin 11) :=
  M11Subgroup_le_alternatingGroup g.2

end Sporadic
