/-
Copyright (c) 2026 Kenta.
Authors: Kenta
AI usage: Developed with assistance from Claude Code (Fable 5, 1M context,
high reasoning).
-/
import FiniteSimpleGroups.Sporadic.M22.Certificates.SteinerSystem

/-!
# The final stabilizer certificate

This file proves that a degree-22 permutation that preserves the candidate
`S(3,6,22)` block set, is even, and fixes the five base points `0,1,2,3,5`
is the identity.

The full automorphism group of the design is `M22:2`; the pointwise
stabilizer of the base inside it has order two, generated by an odd
involution `tauOuter`. The proof therefore splits on `π 4`:

* if `π 4 = 4`, forced block propagation pins every point and `π = 1`;
* if `π 4 = 21`, forced propagation pins `π = tauOuter`, which is odd —
  contradicting evenness.

All propagation steps are Lean-checked `decide` certificates generated by
`scripts/gen_lean_m22_part2.py`.
-/

namespace Sporadic
namespace M22Certificates
namespace FinalStabilizer

open SteinerSystem

/-- The outer involution of `Aut(S(3,6,22)) = M22:2` fixing the base. -/
def tauOuter : Perm22 :=
  List.formPerm ([4, 21] : List (Fin 22)) *
    List.formPerm ([6, 11] : List (Fin 22)) *
    List.formPerm ([7, 17] : List (Fin 22)) *
    List.formPerm ([8, 15] : List (Fin 22)) *
    List.formPerm ([9, 18] : List (Fin 22)) *
    List.formPerm ([10, 16] : List (Fin 22)) *
    List.formPerm ([13, 20] : List (Fin 22))

set_option maxRecDepth 40000 in
/-- The outer involution is odd. -/
theorem tauOuter_sign : Equiv.Perm.sign tauOuter = -1 := by
  decide

set_option maxRecDepth 100000 in
/-- The block `B0` pins `π 4` to `4` or `21` once `0,1,2,3` are fixed. -/
private theorem pin_four :
    ∀ v : Fin 22, v ∈ blockB0 → v ≠ 0 → v ≠ 1 → v ≠ 2 → v ≠ 3 →
      v = 4 ∨ v = 21 := by
  decide

set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqA_21 :
    ∀ i : Fin 77, (1 : Fin 22) ∈ wittBlockAt i →
      (2 : Fin 22) ∈ wittBlockAt i → (5 : Fin 22) ∈ wittBlockAt i →
      i = (21 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atA_21 :
    wittBlockAt (21 : Fin 77) = ({1, 2, 5, 6, 11, 12} : Block) := by
  decide
set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqA_49 :
    ∀ i : Fin 77, (3 : Fin 22) ∈ wittBlockAt i →
      (4 : Fin 22) ∈ wittBlockAt i → (5 : Fin 22) ∈ wittBlockAt i →
      i = (49 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atA_49 :
    wittBlockAt (49 : Fin 77) = ({3, 4, 5, 6, 9, 10} : Block) := by
  decide
private theorem stepA_0 :
    ∀ v : Fin 22, v ∈ ({1, 2, 5, 6, 11, 12} : Block) → v ∈ ({3, 4, 5, 6, 9, 10} : Block) → v ≠ 5 → v = 6 := by
  decide
set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqA_29 :
    ∀ i : Fin 77, (1 : Fin 22) ∈ wittBlockAt i →
      (4 : Fin 22) ∈ wittBlockAt i → (5 : Fin 22) ∈ wittBlockAt i →
      i = (29 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atA_29 :
    wittBlockAt (29 : Fin 77) = ({1, 4, 5, 7, 18, 20} : Block) := by
  decide
set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqA_37 :
    ∀ i : Fin 77, (2 : Fin 22) ∈ wittBlockAt i →
      (3 : Fin 22) ∈ wittBlockAt i → (5 : Fin 22) ∈ wittBlockAt i →
      i = (37 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atA_37 :
    wittBlockAt (37 : Fin 77) = ({2, 3, 5, 7, 17, 19} : Block) := by
  decide
private theorem stepA_1 :
    ∀ v : Fin 22, v ∈ ({1, 4, 5, 7, 18, 20} : Block) → v ∈ ({2, 3, 5, 7, 17, 19} : Block) → v ≠ 5 → v = 7 := by
  decide
set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqA_25 :
    ∀ i : Fin 77, (1 : Fin 22) ∈ wittBlockAt i →
      (3 : Fin 22) ∈ wittBlockAt i → (5 : Fin 22) ∈ wittBlockAt i →
      i = (25 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atA_25 :
    wittBlockAt (25 : Fin 77) = ({1, 3, 5, 8, 14, 15} : Block) := by
  decide
set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqA_41 :
    ∀ i : Fin 77, (2 : Fin 22) ∈ wittBlockAt i →
      (4 : Fin 22) ∈ wittBlockAt i → (5 : Fin 22) ∈ wittBlockAt i →
      i = (41 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atA_41 :
    wittBlockAt (41 : Fin 77) = ({2, 4, 5, 8, 13, 16} : Block) := by
  decide
private theorem stepA_2 :
    ∀ v : Fin 22, v ∈ ({1, 3, 5, 8, 14, 15} : Block) → v ∈ ({2, 4, 5, 8, 13, 16} : Block) → v ≠ 5 → v = 8 := by
  decide
set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqA_5 :
    ∀ i : Fin 77, (0 : Fin 22) ∈ wittBlockAt i →
      (2 : Fin 22) ∈ wittBlockAt i → (5 : Fin 22) ∈ wittBlockAt i →
      i = (5 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atA_5 :
    wittBlockAt (5 : Fin 77) = ({0, 2, 5, 9, 14, 18} : Block) := by
  decide
private theorem stepA_3 :
    ∀ v : Fin 22, v ∈ ({0, 2, 5, 9, 14, 18} : Block) → v ∈ ({3, 4, 5, 6, 9, 10} : Block) → v ≠ 5 → v = 9 := by
  decide
set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqA_1 :
    ∀ i : Fin 77, (0 : Fin 22) ∈ wittBlockAt i →
      (1 : Fin 22) ∈ wittBlockAt i → (5 : Fin 22) ∈ wittBlockAt i →
      i = (1 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atA_1 :
    wittBlockAt (1 : Fin 77) = ({0, 1, 5, 10, 16, 19} : Block) := by
  decide
private theorem stepA_4 :
    ∀ v : Fin 22, v ∈ ({0, 1, 5, 10, 16, 19} : Block) → v ∈ ({3, 4, 5, 6, 9, 10} : Block) → v ≠ 5 → v = 10 := by
  decide
set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqA_13 :
    ∀ i : Fin 77, (0 : Fin 22) ∈ wittBlockAt i →
      (4 : Fin 22) ∈ wittBlockAt i → (5 : Fin 22) ∈ wittBlockAt i →
      i = (13 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atA_13 :
    wittBlockAt (13 : Fin 77) = ({0, 4, 5, 11, 15, 17} : Block) := by
  decide
private theorem stepA_5 :
    ∀ v : Fin 22, v ∈ ({0, 4, 5, 11, 15, 17} : Block) → v ∈ ({1, 2, 5, 6, 11, 12} : Block) → v ≠ 5 → v = 11 := by
  decide
set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqA_9 :
    ∀ i : Fin 77, (0 : Fin 22) ∈ wittBlockAt i →
      (3 : Fin 22) ∈ wittBlockAt i → (5 : Fin 22) ∈ wittBlockAt i →
      i = (9 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atA_9 :
    wittBlockAt (9 : Fin 77) = ({0, 3, 5, 12, 13, 20} : Block) := by
  decide
private theorem stepA_6 :
    ∀ v : Fin 22, v ∈ ({0, 3, 5, 12, 13, 20} : Block) → v ∈ ({1, 2, 5, 6, 11, 12} : Block) → v ≠ 5 → v = 12 := by
  decide
private theorem stepA_7 :
    ∀ v : Fin 22, v ∈ ({0, 3, 5, 12, 13, 20} : Block) → v ∈ ({2, 4, 5, 8, 13, 16} : Block) → v ≠ 5 → v = 13 := by
  decide
private theorem stepA_8 :
    ∀ v : Fin 22, v ∈ ({0, 2, 5, 9, 14, 18} : Block) → v ∈ ({1, 3, 5, 8, 14, 15} : Block) → v ≠ 5 → v = 14 := by
  decide
private theorem stepA_9 :
    ∀ v : Fin 22, v ∈ ({0, 4, 5, 11, 15, 17} : Block) → v ∈ ({1, 3, 5, 8, 14, 15} : Block) → v ≠ 5 → v = 15 := by
  decide
private theorem stepA_10 :
    ∀ v : Fin 22, v ∈ ({0, 1, 5, 10, 16, 19} : Block) → v ∈ ({2, 4, 5, 8, 13, 16} : Block) → v ≠ 5 → v = 16 := by
  decide
private theorem stepA_11 :
    ∀ v : Fin 22, v ∈ ({0, 4, 5, 11, 15, 17} : Block) → v ≠ 0 → v ≠ 4 → v ≠ 5 → v ≠ 11 → v ≠ 15 → v = 17 := by
  decide
private theorem stepA_12 :
    ∀ v : Fin 22, v ∈ ({0, 2, 5, 9, 14, 18} : Block) → v ≠ 0 → v ≠ 2 → v ≠ 5 → v ≠ 9 → v ≠ 14 → v = 18 := by
  decide
private theorem stepA_13 :
    ∀ v : Fin 22, v ∈ ({0, 1, 5, 10, 16, 19} : Block) → v ≠ 0 → v ≠ 1 → v ≠ 5 → v ≠ 10 → v ≠ 16 → v = 19 := by
  decide
private theorem stepA_14 :
    ∀ v : Fin 22, v ∈ ({0, 3, 5, 12, 13, 20} : Block) → v ≠ 0 → v ≠ 3 → v ≠ 5 → v ≠ 12 → v ≠ 13 → v = 20 := by
  decide
set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqA_0 :
    ∀ i : Fin 77, (0 : Fin 22) ∈ wittBlockAt i →
      (1 : Fin 22) ∈ wittBlockAt i → (2 : Fin 22) ∈ wittBlockAt i →
      i = (0 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atA_0 :
    wittBlockAt (0 : Fin 77) = ({0, 1, 2, 3, 4, 21} : Block) := by
  decide
private theorem stepA_15 :
    ∀ v : Fin 22, v ∈ ({0, 1, 2, 3, 4, 21} : Block) → v ≠ 0 → v ≠ 1 → v ≠ 2 → v ≠ 3 → v ≠ 4 → v = 21 := by
  decide

set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqB_21 :
    ∀ i : Fin 77, (1 : Fin 22) ∈ wittBlockAt i →
      (2 : Fin 22) ∈ wittBlockAt i → (5 : Fin 22) ∈ wittBlockAt i →
      i = (21 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atB_21 :
    wittBlockAt (21 : Fin 77) = ({1, 2, 5, 6, 11, 12} : Block) := by
  decide
set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqB_49 :
    ∀ i : Fin 77, (3 : Fin 22) ∈ wittBlockAt i →
      (21 : Fin 22) ∈ wittBlockAt i → (5 : Fin 22) ∈ wittBlockAt i →
      i = (53 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atB_49 :
    wittBlockAt (49 : Fin 77) = ({3, 4, 5, 6, 9, 10} : Block) := by
  decide
set_option maxRecDepth 100000 in
private theorem atB_53 :
    wittBlockAt (53 : Fin 77) = ({3, 5, 11, 16, 18, 21} : Block) := by
  decide
private theorem stepB_0 :
    ∀ v : Fin 22, v ∈ ({1, 2, 5, 6, 11, 12} : Block) → v ∈ ({3, 5, 11, 16, 18, 21} : Block) → v ≠ 5 → v = 11 := by
  decide
set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqB_29 :
    ∀ i : Fin 77, (1 : Fin 22) ∈ wittBlockAt i →
      (21 : Fin 22) ∈ wittBlockAt i → (5 : Fin 22) ∈ wittBlockAt i →
      i = (33 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atB_29 :
    wittBlockAt (29 : Fin 77) = ({1, 4, 5, 7, 18, 20} : Block) := by
  decide
set_option maxRecDepth 100000 in
private theorem atB_33 :
    wittBlockAt (33 : Fin 77) = ({1, 5, 9, 13, 17, 21} : Block) := by
  decide
set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqB_37 :
    ∀ i : Fin 77, (2 : Fin 22) ∈ wittBlockAt i →
      (3 : Fin 22) ∈ wittBlockAt i → (5 : Fin 22) ∈ wittBlockAt i →
      i = (37 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atB_37 :
    wittBlockAt (37 : Fin 77) = ({2, 3, 5, 7, 17, 19} : Block) := by
  decide
private theorem stepB_1 :
    ∀ v : Fin 22, v ∈ ({1, 5, 9, 13, 17, 21} : Block) → v ∈ ({2, 3, 5, 7, 17, 19} : Block) → v ≠ 5 → v = 17 := by
  decide
set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqB_25 :
    ∀ i : Fin 77, (1 : Fin 22) ∈ wittBlockAt i →
      (3 : Fin 22) ∈ wittBlockAt i → (5 : Fin 22) ∈ wittBlockAt i →
      i = (25 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atB_25 :
    wittBlockAt (25 : Fin 77) = ({1, 3, 5, 8, 14, 15} : Block) := by
  decide
set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqB_41 :
    ∀ i : Fin 77, (2 : Fin 22) ∈ wittBlockAt i →
      (21 : Fin 22) ∈ wittBlockAt i → (5 : Fin 22) ∈ wittBlockAt i →
      i = (45 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atB_41 :
    wittBlockAt (41 : Fin 77) = ({2, 4, 5, 8, 13, 16} : Block) := by
  decide
set_option maxRecDepth 100000 in
private theorem atB_45 :
    wittBlockAt (45 : Fin 77) = ({2, 5, 10, 15, 20, 21} : Block) := by
  decide
private theorem stepB_2 :
    ∀ v : Fin 22, v ∈ ({1, 3, 5, 8, 14, 15} : Block) → v ∈ ({2, 5, 10, 15, 20, 21} : Block) → v ≠ 5 → v = 15 := by
  decide
set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqB_5 :
    ∀ i : Fin 77, (0 : Fin 22) ∈ wittBlockAt i →
      (2 : Fin 22) ∈ wittBlockAt i → (5 : Fin 22) ∈ wittBlockAt i →
      i = (5 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atB_5 :
    wittBlockAt (5 : Fin 77) = ({0, 2, 5, 9, 14, 18} : Block) := by
  decide
private theorem stepB_3 :
    ∀ v : Fin 22, v ∈ ({0, 2, 5, 9, 14, 18} : Block) → v ∈ ({3, 5, 11, 16, 18, 21} : Block) → v ≠ 5 → v = 18 := by
  decide
set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqB_1 :
    ∀ i : Fin 77, (0 : Fin 22) ∈ wittBlockAt i →
      (1 : Fin 22) ∈ wittBlockAt i → (5 : Fin 22) ∈ wittBlockAt i →
      i = (1 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atB_1 :
    wittBlockAt (1 : Fin 77) = ({0, 1, 5, 10, 16, 19} : Block) := by
  decide
private theorem stepB_4 :
    ∀ v : Fin 22, v ∈ ({0, 1, 5, 10, 16, 19} : Block) → v ∈ ({3, 5, 11, 16, 18, 21} : Block) → v ≠ 5 → v = 16 := by
  decide
set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqB_13 :
    ∀ i : Fin 77, (0 : Fin 22) ∈ wittBlockAt i →
      (21 : Fin 22) ∈ wittBlockAt i → (5 : Fin 22) ∈ wittBlockAt i →
      i = (17 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atB_13 :
    wittBlockAt (13 : Fin 77) = ({0, 4, 5, 11, 15, 17} : Block) := by
  decide
set_option maxRecDepth 100000 in
private theorem atB_17 :
    wittBlockAt (17 : Fin 77) = ({0, 5, 6, 7, 8, 21} : Block) := by
  decide
private theorem stepB_5 :
    ∀ v : Fin 22, v ∈ ({0, 5, 6, 7, 8, 21} : Block) → v ∈ ({1, 2, 5, 6, 11, 12} : Block) → v ≠ 5 → v = 6 := by
  decide
set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqB_9 :
    ∀ i : Fin 77, (0 : Fin 22) ∈ wittBlockAt i →
      (3 : Fin 22) ∈ wittBlockAt i → (5 : Fin 22) ∈ wittBlockAt i →
      i = (9 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atB_9 :
    wittBlockAt (9 : Fin 77) = ({0, 3, 5, 12, 13, 20} : Block) := by
  decide
private theorem stepB_6 :
    ∀ v : Fin 22, v ∈ ({0, 3, 5, 12, 13, 20} : Block) → v ∈ ({1, 2, 5, 6, 11, 12} : Block) → v ≠ 5 → v = 12 := by
  decide
private theorem stepB_7 :
    ∀ v : Fin 22, v ∈ ({0, 3, 5, 12, 13, 20} : Block) → v ∈ ({2, 5, 10, 15, 20, 21} : Block) → v ≠ 5 → v = 20 := by
  decide
private theorem stepB_8 :
    ∀ v : Fin 22, v ∈ ({0, 2, 5, 9, 14, 18} : Block) → v ∈ ({1, 3, 5, 8, 14, 15} : Block) → v ≠ 5 → v = 14 := by
  decide
private theorem stepB_9 :
    ∀ v : Fin 22, v ∈ ({0, 5, 6, 7, 8, 21} : Block) → v ∈ ({1, 3, 5, 8, 14, 15} : Block) → v ≠ 5 → v = 8 := by
  decide
private theorem stepB_10 :
    ∀ v : Fin 22, v ∈ ({0, 1, 5, 10, 16, 19} : Block) → v ∈ ({2, 5, 10, 15, 20, 21} : Block) → v ≠ 5 → v = 10 := by
  decide
private theorem stepB_11 :
    ∀ v : Fin 22, v ∈ ({0, 5, 6, 7, 8, 21} : Block) → v ≠ 0 → v ≠ 21 → v ≠ 5 → v ≠ 6 → v ≠ 8 → v = 7 := by
  decide
private theorem stepB_12 :
    ∀ v : Fin 22, v ∈ ({0, 2, 5, 9, 14, 18} : Block) → v ≠ 0 → v ≠ 2 → v ≠ 5 → v ≠ 18 → v ≠ 14 → v = 9 := by
  decide
private theorem stepB_13 :
    ∀ v : Fin 22, v ∈ ({0, 1, 5, 10, 16, 19} : Block) → v ≠ 0 → v ≠ 1 → v ≠ 5 → v ≠ 16 → v ≠ 10 → v = 19 := by
  decide
private theorem stepB_14 :
    ∀ v : Fin 22, v ∈ ({0, 3, 5, 12, 13, 20} : Block) → v ≠ 0 → v ≠ 3 → v ≠ 5 → v ≠ 12 → v ≠ 20 → v = 13 := by
  decide
set_option maxHeartbeats 1600000 in
-- The indexed uniqueness certificate is intentionally checked by computation.
set_option maxRecDepth 200000 in
private theorem uniqB_0 :
    ∀ i : Fin 77, (0 : Fin 22) ∈ wittBlockAt i →
      (1 : Fin 22) ∈ wittBlockAt i → (2 : Fin 22) ∈ wittBlockAt i →
      i = (0 : Fin 77) := by
  decide
set_option maxRecDepth 100000 in
private theorem atB_0 :
    wittBlockAt (0 : Fin 77) = ({0, 1, 2, 3, 4, 21} : Block) := by
  decide
private theorem stepB_15 :
    ∀ v : Fin 22, v ∈ ({0, 1, 2, 3, 4, 21} : Block) → v ≠ 0 → v ≠ 1 → v ≠ 2 → v ≠ 3 → v ≠ 21 → v = 4 := by
  decide

/-- Branch `π 4 = 4`: forced propagation yields the identity. -/
theorem eq_one_of_fix_four (π : Perm22)
    (hpres : ∀ B ∈ wittBlockList, blockMap π B ∈ wittBlocks)
    (h0 : π 0 = 0) (h1 : π 1 = 1) (h2 : π 2 = 2) (h3 : π 3 = 3)
    (h5 : π 5 = 5) (h4 : π 4 = 4) : π = 1 := by
  have hKBA_21 : blockMap π ({1, 2, 5, 6, 11, 12} : Block) = ({1, 2, 5, 6, 11, 12} : Block) :=
    blockMap_eq_of_three π hpres atA_21 (by decide) (by decide) (by decide)
      h1 h2 h5 uniqA_21 atA_21
  have hKBA_49 : blockMap π ({3, 4, 5, 6, 9, 10} : Block) = ({3, 4, 5, 6, 9, 10} : Block) :=
    blockMap_eq_of_three π hpres atA_49 (by decide) (by decide) (by decide)
      h3 h4 h5 uniqA_49 atA_49
  have hvA_6 : π 6 = 6 :=
    stepA_0 _ (mem_of_blockMap_eq π hKBA_21 (by decide)) (mem_of_blockMap_eq π hKBA_49 (by decide)) (ne_of_value π h5 (by decide))
  have hKBA_29 : blockMap π ({1, 4, 5, 7, 18, 20} : Block) = ({1, 4, 5, 7, 18, 20} : Block) :=
    blockMap_eq_of_three π hpres atA_29 (by decide) (by decide) (by decide)
      h1 h4 h5 uniqA_29 atA_29
  have hKBA_37 : blockMap π ({2, 3, 5, 7, 17, 19} : Block) = ({2, 3, 5, 7, 17, 19} : Block) :=
    blockMap_eq_of_three π hpres atA_37 (by decide) (by decide) (by decide)
      h2 h3 h5 uniqA_37 atA_37
  have hvA_7 : π 7 = 7 :=
    stepA_1 _ (mem_of_blockMap_eq π hKBA_29 (by decide)) (mem_of_blockMap_eq π hKBA_37 (by decide)) (ne_of_value π h5 (by decide))
  have hKBA_25 : blockMap π ({1, 3, 5, 8, 14, 15} : Block) = ({1, 3, 5, 8, 14, 15} : Block) :=
    blockMap_eq_of_three π hpres atA_25 (by decide) (by decide) (by decide)
      h1 h3 h5 uniqA_25 atA_25
  have hKBA_41 : blockMap π ({2, 4, 5, 8, 13, 16} : Block) = ({2, 4, 5, 8, 13, 16} : Block) :=
    blockMap_eq_of_three π hpres atA_41 (by decide) (by decide) (by decide)
      h2 h4 h5 uniqA_41 atA_41
  have hvA_8 : π 8 = 8 :=
    stepA_2 _ (mem_of_blockMap_eq π hKBA_25 (by decide)) (mem_of_blockMap_eq π hKBA_41 (by decide)) (ne_of_value π h5 (by decide))
  have hKBA_5 : blockMap π ({0, 2, 5, 9, 14, 18} : Block) = ({0, 2, 5, 9, 14, 18} : Block) :=
    blockMap_eq_of_three π hpres atA_5 (by decide) (by decide) (by decide)
      h0 h2 h5 uniqA_5 atA_5
  have hvA_9 : π 9 = 9 :=
    stepA_3 _ (mem_of_blockMap_eq π hKBA_5 (by decide)) (mem_of_blockMap_eq π hKBA_49 (by decide)) (ne_of_value π h5 (by decide))
  have hKBA_1 : blockMap π ({0, 1, 5, 10, 16, 19} : Block) = ({0, 1, 5, 10, 16, 19} : Block) :=
    blockMap_eq_of_three π hpres atA_1 (by decide) (by decide) (by decide)
      h0 h1 h5 uniqA_1 atA_1
  have hvA_10 : π 10 = 10 :=
    stepA_4 _ (mem_of_blockMap_eq π hKBA_1 (by decide)) (mem_of_blockMap_eq π hKBA_49 (by decide)) (ne_of_value π h5 (by decide))
  have hKBA_13 : blockMap π ({0, 4, 5, 11, 15, 17} : Block) = ({0, 4, 5, 11, 15, 17} : Block) :=
    blockMap_eq_of_three π hpres atA_13 (by decide) (by decide) (by decide)
      h0 h4 h5 uniqA_13 atA_13
  have hvA_11 : π 11 = 11 :=
    stepA_5 _ (mem_of_blockMap_eq π hKBA_13 (by decide)) (mem_of_blockMap_eq π hKBA_21 (by decide)) (ne_of_value π h5 (by decide))
  have hKBA_9 : blockMap π ({0, 3, 5, 12, 13, 20} : Block) = ({0, 3, 5, 12, 13, 20} : Block) :=
    blockMap_eq_of_three π hpres atA_9 (by decide) (by decide) (by decide)
      h0 h3 h5 uniqA_9 atA_9
  have hvA_12 : π 12 = 12 :=
    stepA_6 _ (mem_of_blockMap_eq π hKBA_9 (by decide)) (mem_of_blockMap_eq π hKBA_21 (by decide)) (ne_of_value π h5 (by decide))
  have hvA_13 : π 13 = 13 :=
    stepA_7 _ (mem_of_blockMap_eq π hKBA_9 (by decide)) (mem_of_blockMap_eq π hKBA_41 (by decide)) (ne_of_value π h5 (by decide))
  have hvA_14 : π 14 = 14 :=
    stepA_8 _ (mem_of_blockMap_eq π hKBA_5 (by decide)) (mem_of_blockMap_eq π hKBA_25 (by decide)) (ne_of_value π h5 (by decide))
  have hvA_15 : π 15 = 15 :=
    stepA_9 _ (mem_of_blockMap_eq π hKBA_13 (by decide)) (mem_of_blockMap_eq π hKBA_25 (by decide)) (ne_of_value π h5 (by decide))
  have hvA_16 : π 16 = 16 :=
    stepA_10 _ (mem_of_blockMap_eq π hKBA_1 (by decide)) (mem_of_blockMap_eq π hKBA_41 (by decide)) (ne_of_value π h5 (by decide))
  have hvA_17 : π 17 = 17 :=
    stepA_11 _ (mem_of_blockMap_eq π hKBA_13 (by decide)) (ne_of_value π h0 (by decide)) (ne_of_value π h4 (by decide)) (ne_of_value π h5 (by decide)) (ne_of_value π hvA_11 (by decide)) (ne_of_value π hvA_15 (by decide))
  have hvA_18 : π 18 = 18 :=
    stepA_12 _ (mem_of_blockMap_eq π hKBA_5 (by decide)) (ne_of_value π h0 (by decide)) (ne_of_value π h2 (by decide)) (ne_of_value π h5 (by decide)) (ne_of_value π hvA_9 (by decide)) (ne_of_value π hvA_14 (by decide))
  have hvA_19 : π 19 = 19 :=
    stepA_13 _ (mem_of_blockMap_eq π hKBA_1 (by decide)) (ne_of_value π h0 (by decide)) (ne_of_value π h1 (by decide)) (ne_of_value π h5 (by decide)) (ne_of_value π hvA_10 (by decide)) (ne_of_value π hvA_16 (by decide))
  have hvA_20 : π 20 = 20 :=
    stepA_14 _ (mem_of_blockMap_eq π hKBA_9 (by decide)) (ne_of_value π h0 (by decide)) (ne_of_value π h3 (by decide)) (ne_of_value π h5 (by decide)) (ne_of_value π hvA_12 (by decide)) (ne_of_value π hvA_13 (by decide))
  have hKBA_0 : blockMap π ({0, 1, 2, 3, 4, 21} : Block) = ({0, 1, 2, 3, 4, 21} : Block) :=
    blockMap_eq_of_three π hpres atA_0 (by decide) (by decide) (by decide)
      h0 h1 h2 uniqA_0 atA_0
  have hvA_21 : π 21 = 21 :=
    stepA_15 _ (mem_of_blockMap_eq π hKBA_0 (by decide)) (ne_of_value π h0 (by decide)) (ne_of_value π h1 (by decide)) (ne_of_value π h2 (by decide)) (ne_of_value π h3 (by decide)) (ne_of_value π h4 (by decide))
  apply Equiv.ext
  intro x
  fin_cases x
  · exact h0.trans (by decide)
  · exact h1.trans (by decide)
  · exact h2.trans (by decide)
  · exact h3.trans (by decide)
  · exact h4.trans (by decide)
  · exact h5.trans (by decide)
  · exact hvA_6.trans (by decide)
  · exact hvA_7.trans (by decide)
  · exact hvA_8.trans (by decide)
  · exact hvA_9.trans (by decide)
  · exact hvA_10.trans (by decide)
  · exact hvA_11.trans (by decide)
  · exact hvA_12.trans (by decide)
  · exact hvA_13.trans (by decide)
  · exact hvA_14.trans (by decide)
  · exact hvA_15.trans (by decide)
  · exact hvA_16.trans (by decide)
  · exact hvA_17.trans (by decide)
  · exact hvA_18.trans (by decide)
  · exact hvA_19.trans (by decide)
  · exact hvA_20.trans (by decide)
  · exact hvA_21.trans (by decide)

/-- Branch `π 4 = 21`: forced propagation yields the outer involution. -/
theorem eq_tau_of_swap_four (π : Perm22)
    (hpres : ∀ B ∈ wittBlockList, blockMap π B ∈ wittBlocks)
    (h0 : π 0 = 0) (h1 : π 1 = 1) (h2 : π 2 = 2) (h3 : π 3 = 3)
    (h5 : π 5 = 5) (h4 : π 4 = 21) : π = tauOuter := by
  have hKBB_21 : blockMap π ({1, 2, 5, 6, 11, 12} : Block) = ({1, 2, 5, 6, 11, 12} : Block) :=
    blockMap_eq_of_three π hpres atB_21 (by decide) (by decide) (by decide)
      h1 h2 h5 uniqB_21 atB_21
  have hKBB_49 : blockMap π ({3, 4, 5, 6, 9, 10} : Block) = ({3, 5, 11, 16, 18, 21} : Block) :=
    blockMap_eq_of_three π hpres atB_49 (by decide) (by decide) (by decide)
      h3 h4 h5 uniqB_49 atB_53
  have hvB_6 : π 6 = 11 :=
    stepB_0 _ (mem_of_blockMap_eq π hKBB_21 (by decide)) (mem_of_blockMap_eq π hKBB_49 (by decide)) (ne_of_value π h5 (by decide))
  have hKBB_29 : blockMap π ({1, 4, 5, 7, 18, 20} : Block) = ({1, 5, 9, 13, 17, 21} : Block) :=
    blockMap_eq_of_three π hpres atB_29 (by decide) (by decide) (by decide)
      h1 h4 h5 uniqB_29 atB_33
  have hKBB_37 : blockMap π ({2, 3, 5, 7, 17, 19} : Block) = ({2, 3, 5, 7, 17, 19} : Block) :=
    blockMap_eq_of_three π hpres atB_37 (by decide) (by decide) (by decide)
      h2 h3 h5 uniqB_37 atB_37
  have hvB_7 : π 7 = 17 :=
    stepB_1 _ (mem_of_blockMap_eq π hKBB_29 (by decide)) (mem_of_blockMap_eq π hKBB_37 (by decide)) (ne_of_value π h5 (by decide))
  have hKBB_25 : blockMap π ({1, 3, 5, 8, 14, 15} : Block) = ({1, 3, 5, 8, 14, 15} : Block) :=
    blockMap_eq_of_three π hpres atB_25 (by decide) (by decide) (by decide)
      h1 h3 h5 uniqB_25 atB_25
  have hKBB_41 : blockMap π ({2, 4, 5, 8, 13, 16} : Block) = ({2, 5, 10, 15, 20, 21} : Block) :=
    blockMap_eq_of_three π hpres atB_41 (by decide) (by decide) (by decide)
      h2 h4 h5 uniqB_41 atB_45
  have hvB_8 : π 8 = 15 :=
    stepB_2 _ (mem_of_blockMap_eq π hKBB_25 (by decide)) (mem_of_blockMap_eq π hKBB_41 (by decide)) (ne_of_value π h5 (by decide))
  have hKBB_5 : blockMap π ({0, 2, 5, 9, 14, 18} : Block) = ({0, 2, 5, 9, 14, 18} : Block) :=
    blockMap_eq_of_three π hpres atB_5 (by decide) (by decide) (by decide)
      h0 h2 h5 uniqB_5 atB_5
  have hvB_9 : π 9 = 18 :=
    stepB_3 _ (mem_of_blockMap_eq π hKBB_5 (by decide)) (mem_of_blockMap_eq π hKBB_49 (by decide)) (ne_of_value π h5 (by decide))
  have hKBB_1 : blockMap π ({0, 1, 5, 10, 16, 19} : Block) = ({0, 1, 5, 10, 16, 19} : Block) :=
    blockMap_eq_of_three π hpres atB_1 (by decide) (by decide) (by decide)
      h0 h1 h5 uniqB_1 atB_1
  have hvB_10 : π 10 = 16 :=
    stepB_4 _ (mem_of_blockMap_eq π hKBB_1 (by decide)) (mem_of_blockMap_eq π hKBB_49 (by decide)) (ne_of_value π h5 (by decide))
  have hKBB_13 : blockMap π ({0, 4, 5, 11, 15, 17} : Block) = ({0, 5, 6, 7, 8, 21} : Block) :=
    blockMap_eq_of_three π hpres atB_13 (by decide) (by decide) (by decide)
      h0 h4 h5 uniqB_13 atB_17
  have hvB_11 : π 11 = 6 :=
    stepB_5 _ (mem_of_blockMap_eq π hKBB_13 (by decide)) (mem_of_blockMap_eq π hKBB_21 (by decide)) (ne_of_value π h5 (by decide))
  have hKBB_9 : blockMap π ({0, 3, 5, 12, 13, 20} : Block) = ({0, 3, 5, 12, 13, 20} : Block) :=
    blockMap_eq_of_three π hpres atB_9 (by decide) (by decide) (by decide)
      h0 h3 h5 uniqB_9 atB_9
  have hvB_12 : π 12 = 12 :=
    stepB_6 _ (mem_of_blockMap_eq π hKBB_9 (by decide)) (mem_of_blockMap_eq π hKBB_21 (by decide)) (ne_of_value π h5 (by decide))
  have hvB_13 : π 13 = 20 :=
    stepB_7 _ (mem_of_blockMap_eq π hKBB_9 (by decide)) (mem_of_blockMap_eq π hKBB_41 (by decide)) (ne_of_value π h5 (by decide))
  have hvB_14 : π 14 = 14 :=
    stepB_8 _ (mem_of_blockMap_eq π hKBB_5 (by decide)) (mem_of_blockMap_eq π hKBB_25 (by decide)) (ne_of_value π h5 (by decide))
  have hvB_15 : π 15 = 8 :=
    stepB_9 _ (mem_of_blockMap_eq π hKBB_13 (by decide)) (mem_of_blockMap_eq π hKBB_25 (by decide)) (ne_of_value π h5 (by decide))
  have hvB_16 : π 16 = 10 :=
    stepB_10 _ (mem_of_blockMap_eq π hKBB_1 (by decide)) (mem_of_blockMap_eq π hKBB_41 (by decide)) (ne_of_value π h5 (by decide))
  have hvB_17 : π 17 = 7 :=
    stepB_11 _ (mem_of_blockMap_eq π hKBB_13 (by decide)) (ne_of_value π h0 (by decide)) (ne_of_value π h4 (by decide)) (ne_of_value π h5 (by decide)) (ne_of_value π hvB_11 (by decide)) (ne_of_value π hvB_15 (by decide))
  have hvB_18 : π 18 = 9 :=
    stepB_12 _ (mem_of_blockMap_eq π hKBB_5 (by decide)) (ne_of_value π h0 (by decide)) (ne_of_value π h2 (by decide)) (ne_of_value π h5 (by decide)) (ne_of_value π hvB_9 (by decide)) (ne_of_value π hvB_14 (by decide))
  have hvB_19 : π 19 = 19 :=
    stepB_13 _ (mem_of_blockMap_eq π hKBB_1 (by decide)) (ne_of_value π h0 (by decide)) (ne_of_value π h1 (by decide)) (ne_of_value π h5 (by decide)) (ne_of_value π hvB_10 (by decide)) (ne_of_value π hvB_16 (by decide))
  have hvB_20 : π 20 = 13 :=
    stepB_14 _ (mem_of_blockMap_eq π hKBB_9 (by decide)) (ne_of_value π h0 (by decide)) (ne_of_value π h3 (by decide)) (ne_of_value π h5 (by decide)) (ne_of_value π hvB_12 (by decide)) (ne_of_value π hvB_13 (by decide))
  have hKBB_0 : blockMap π ({0, 1, 2, 3, 4, 21} : Block) = ({0, 1, 2, 3, 4, 21} : Block) :=
    blockMap_eq_of_three π hpres atB_0 (by decide) (by decide) (by decide)
      h0 h1 h2 uniqB_0 atB_0
  have hvB_21 : π 21 = 4 :=
    stepB_15 _ (mem_of_blockMap_eq π hKBB_0 (by decide)) (ne_of_value π h0 (by decide)) (ne_of_value π h1 (by decide)) (ne_of_value π h2 (by decide)) (ne_of_value π h3 (by decide)) (ne_of_value π h4 (by decide))
  apply Equiv.ext
  intro x
  fin_cases x
  · exact h0.trans (by decide)
  · exact h1.trans (by decide)
  · exact h2.trans (by decide)
  · exact h3.trans (by decide)
  · exact h4.trans (by decide)
  · exact h5.trans (by decide)
  · exact hvB_6.trans (by decide)
  · exact hvB_7.trans (by decide)
  · exact hvB_8.trans (by decide)
  · exact hvB_9.trans (by decide)
  · exact hvB_10.trans (by decide)
  · exact hvB_11.trans (by decide)
  · exact hvB_12.trans (by decide)
  · exact hvB_13.trans (by decide)
  · exact hvB_14.trans (by decide)
  · exact hvB_15.trans (by decide)
  · exact hvB_16.trans (by decide)
  · exact hvB_17.trans (by decide)
  · exact hvB_18.trans (by decide)
  · exact hvB_19.trans (by decide)
  · exact hvB_20.trans (by decide)
  · exact hvB_21.trans (by decide)

/--
Any even degree-22 permutation that preserves the checked blocks and fixes
`0,1,2,3,5` is the identity. This is the ambient final-stabilizer certificate.
-/
theorem fixed_base_preserves_wittBlocks_eq_one (π : Perm22)
    (hg : PreservesWittBlocks π) (hsign : Equiv.Perm.sign π = 1)
    (h0 : π 0 = 0) (h1 : π 1 = 1) (h2 : π 2 = 2) (h3 : π 3 = 3)
    (h5 : π 5 = 5) : π = 1 := by
  have hpres := hg.1
  have hKB0 : blockMap π blockB0 = blockB0 :=
    blockMap_eq_of_three π hpres wittBlockAt_zero (by decide) (by decide)
      (by decide) h0 h1 h2 unique_block_012 wittBlockAt_zero
  have hmem4 : π 4 ∈ blockB0 := mem_of_blockMap_eq π hKB0 (by decide)
  have h4or : π 4 = 4 ∨ π 4 = 21 :=
    pin_four _ hmem4
      (ne_of_value π h0 (by decide)) (ne_of_value π h1 (by decide))
      (ne_of_value π h2 (by decide)) (ne_of_value π h3 (by decide))
  rcases h4or with h4 | h4
  · exact eq_one_of_fix_four π hpres h0 h1 h2 h3 h5 h4
  · exfalso
    have htau := eq_tau_of_swap_four π hpres h0 h1 h2 h3 h5 h4
    rw [htau, tauOuter_sign] at hsign
    exact absurd hsign (by decide)

end FinalStabilizer
end M22Certificates
end Sporadic
