/-
Copyright (c) 2026 Kenta.
Authors: Kenta
AI usage: Developed with assistance from Claude Code (Fable 5, 1M context,
high reasoning).
-/
import Mathlib.GroupTheory.Perm.Cycle.Concrete
import Mathlib.Algebra.Group.Subgroup.Finite
import Mathlib.GroupTheory.Subgroup.Simple
import FiniteSimpleGroups.Sporadic.M22.Basic

/-!
# L34: a concrete copy of PSL(3,4) on 21 points

Three explicit elations of PG(2,4) (computed by `scripts/gen_l34.py` and
verified there to generate a group of order 20160). Lean re-verifies all
certificate claims by `decide`.
-/

namespace Sporadic
namespace L34

/-- The ambient permutation group for the 21-point action. -/
abbrev Perm21 : Type := Equiv.Perm (Fin 21)

/-- Elation generator 1 (an involution; 8 transpositions). -/
def l34e1 : Perm21 :=
  List.formPerm ([0, 18] : List (Fin 21)) *
    List.formPerm ([2, 10] : List (Fin 21)) *
    List.formPerm ([3, 14] : List (Fin 21)) *
    List.formPerm ([4, 6] : List (Fin 21)) *
    List.formPerm ([5, 15] : List (Fin 21)) *
    List.formPerm ([7, 9] : List (Fin 21)) *
    List.formPerm ([11, 13] : List (Fin 21)) *
    List.formPerm ([17, 19] : List (Fin 21))

/-- Elation generator 2 (an involution; 8 transpositions). -/
def l34e2 : Perm21 :=
  List.formPerm ([0, 20] : List (Fin 21)) *
    List.formPerm ([1, 14] : List (Fin 21)) *
    List.formPerm ([2, 7] : List (Fin 21)) *
    List.formPerm ([4, 9] : List (Fin 21)) *
    List.formPerm ([6, 10] : List (Fin 21)) *
    List.formPerm ([8, 15] : List (Fin 21)) *
    List.formPerm ([12, 13] : List (Fin 21)) *
    List.formPerm ([17, 19] : List (Fin 21))

/-- Elation generator 3 (an involution; 8 transpositions). -/
def l34e3 : Perm21 :=
  List.formPerm ([0, 13] : List (Fin 21)) *
    List.formPerm ([1, 10] : List (Fin 21)) *
    List.formPerm ([2, 8] : List (Fin 21)) *
    List.formPerm ([4, 19] : List (Fin 21)) *
    List.formPerm ([5, 12] : List (Fin 21)) *
    List.formPerm ([6, 18] : List (Fin 21)) *
    List.formPerm ([11, 17] : List (Fin 21)) *
    List.formPerm ([15, 16] : List (Fin 21))

/-- The subgroup generated by the three elations: a copy of `PSL(3,4)`. -/
def L34Subgroup : Subgroup Perm21 :=
  Subgroup.closure ({l34e1, l34e2, l34e3} : Set Perm21)

instance instGroupL34 : Group L34Subgroup :=
  inferInstance

noncomputable instance instFintypeL34 : Fintype L34Subgroup := by
  classical
  infer_instance

theorem l34e1_mem : l34e1 ∈ L34Subgroup :=
  Subgroup.subset_closure (by simp)

theorem l34e2_mem : l34e2 ∈ L34Subgroup :=
  Subgroup.subset_closure (by simp)

theorem l34e3_mem : l34e3 ∈ L34Subgroup :=
  Subgroup.subset_closure (by simp)

set_option maxRecDepth 20000 in
/-- The first generator is an involution. -/
theorem l34e1_sq : l34e1 * l34e1 = 1 := by
  apply Equiv.ext
  decide

set_option maxRecDepth 20000 in
/-- The second generator is an involution. -/
theorem l34e2_sq : l34e2 * l34e2 = 1 := by
  apply Equiv.ext
  decide

set_option maxRecDepth 20000 in
/-- The third generator is an involution. -/
theorem l34e3_sq : l34e3 * l34e3 = 1 := by
  apply Equiv.ext
  decide

theorem l34e1_inv : l34e1⁻¹ = l34e1 :=
  inv_eq_of_mul_eq_one_right l34e1_sq

theorem l34e2_inv : l34e2⁻¹ = l34e2 :=
  inv_eq_of_mul_eq_one_right l34e2_sq

theorem l34e3_inv : l34e3⁻¹ = l34e3 :=
  inv_eq_of_mul_eq_one_right l34e3_sq

end L34
end Sporadic
