/-
Copyright (c) 2026 Kenta.
Authors: Kenta
AI usage: Developed with assistance from Claude Code (Fable 5, 1M context,
high reasoning).
-/
import Mathlib.GroupTheory.Commutator.Basic
import Mathlib.GroupTheory.QuotientGroup.Basic
import FiniteSimpleGroups.Sporadic.M22.L34.Elations
import FiniteSimpleGroups.Sporadic.M22.L34.Cardinality

/-!
# Simplicity of L34 (= PSL(3,4)) by the Iwasawa argument

Let `N` be a nontrivial normal subgroup of `L34`.

1. Two-transitivity word certificates make `N` transitive on the 21 points.
2. `T0` is the (abelian) group generated by the fifteen elations at the base
   point `0`. By elation equivariance, conjugating `T0` by an element moving
   `0` to `x` yields the elation group at `x`.
3. Every group element decomposes as `n * t` with `n ∈ N`, `t ∈ T0`:
   the generators are elations, hence conjugates of base elations by
   elements of `N` (transitivity), and the decomposition property is closed
   under products and inverses.
4. Hence `L34 ⧸ N` is generated by the abelian image of `T0`, so every
   commutator lies in `N`.
5. The commutator identities `l34eI = ⁅u,v⁆` (elations) make `L34` perfect.
6. Therefore `N = ⊤`.
-/

open scoped commutatorElement

namespace Sporadic
namespace L34

/-! ## Permutation helpers -/

theorem perm_apply_inv_self (f : Perm21) (x : Fin 21) : f (f⁻¹ x) = x :=
  Equiv.Perm.eq_inv_iff_eq.mp rfl

theorem perm_inv_apply_self (f : Perm21) (x : Fin 21) : f⁻¹ (f x) = x :=
  Equiv.Perm.inv_eq_iff_eq.mpr rfl

/-! ## The generators are elations -/

set_option maxRecDepth 40000 in
/-- The first generator is the elation at center `20`, index `7`. -/
theorem l34e1_eq_elation : l34e1 = elationAt 20 7 := by
  apply Equiv.ext
  decide +kernel

set_option maxRecDepth 40000 in
/-- The second generator is the elation at center `18`, index `14`. -/
theorem l34e2_eq_elation : l34e2 = elationAt 18 14 := by
  apply Equiv.ext
  decide +kernel

set_option maxRecDepth 40000 in
/-- The third generator is the elation at center `14`, index `5`. -/
theorem l34e3_eq_elation : l34e3 = elationAt 14 5 := by
  apply Equiv.ext
  decide +kernel

/-! ## Two-transitivity -/

theorem pair_witness_from_base (x y : Fin 21) (hxy : x ≠ y) :
    ∃ g : L34Subgroup, g.1 0 = x ∧ g.1 1 = y := by
  classical
  set A := Word.toL34 (orbitZeroWord x) with hA
  have hA0 : A.1 (0 : Fin 21) = x := by
    simpa [hA] using orbitZeroWord_maps_zero_all x
  set z := A.1⁻¹ y with hzdef
  have hz0 : z ≠ 0 := by
    intro h
    apply hxy
    have : y = A.1 (0 : Fin 21) := by
      rw [← h, hzdef, perm_apply_inv_self]
    rw [this, hA0]
  set B := Word.toL34 (zeroStabWord z) with hB
  have hBfix : B.1 (0 : Fin 21) = 0 := by
    simpa [hB] using zeroStabWord_fixes_zero_all z hz0
  have hBone : B.1 (1 : Fin 21) = z := by
    simpa [hB] using zeroStabWord_maps_one_all z hz0
  refine ⟨A * B, ?_, ?_⟩
  · change (A.1 * B.1) 0 = x
    rw [Equiv.Perm.mul_apply, hBfix, hA0]
  · change (A.1 * B.1) 1 = y
    rw [Equiv.Perm.mul_apply, hBone, hzdef, perm_apply_inv_self]

theorem pair_witness (p q u v : Fin 21) (hpq : p ≠ q) (huv : u ≠ v) :
    ∃ g : L34Subgroup, g.1 p = u ∧ g.1 q = v := by
  obtain ⟨g1, h1p, h1q⟩ := pair_witness_from_base p q hpq
  obtain ⟨g2, h2u, h2v⟩ := pair_witness_from_base u v huv
  have hinvp : g1.1⁻¹ p = 0 := by
    rw [← h1p, perm_inv_apply_self]
  have hinvq : g1.1⁻¹ q = 1 := by
    rw [← h1q, perm_inv_apply_self]
  refine ⟨g2 * g1⁻¹, ?_, ?_⟩
  · change (g2.1 * g1.1⁻¹) p = u
    rw [Equiv.Perm.mul_apply, hinvp, h2u]
  · change (g2.1 * g1.1⁻¹) q = v
    rw [Equiv.Perm.mul_apply, hinvq, h2v]

/-! ## Transitivity of nontrivial normal subgroups -/

theorem exists_moved_of_ne_bot (N : Subgroup L34Subgroup) (hbot : N ≠ ⊥) :
    ∃ n ∈ N, ∃ p : Fin 21, n.1 p ≠ p := by
  by_contra h
  push Not at h
  apply hbot
  rw [eq_bot_iff]
  intro n hn
  rw [Subgroup.mem_bot]
  apply Subtype.ext
  apply Equiv.ext
  intro p
  simpa using h n hn p

theorem normal_orbit_witness (N : Subgroup L34Subgroup) (hN : N.Normal)
    {n : L34Subgroup} (hnN : n ∈ N) {p : Fin 21} (hp : n.1 p ≠ p) (u v : Fin 21) :
    ∃ m ∈ N, m.1 u = v := by
  by_cases huv : u = v
  · exact ⟨1, N.one_mem, by simp [huv]⟩
  · obtain ⟨g, hgp, hgq⟩ := pair_witness p (n.1 p) u v (Ne.symm hp) huv
    refine ⟨g * n * g⁻¹, hN.conj_mem n hnN g, ?_⟩
    have hinv : g.1⁻¹ u = p := by
      rw [← hgp, perm_inv_apply_self]
    change (g.1 * n.1 * g.1⁻¹) u = v
    rw [Equiv.Perm.mul_apply, Equiv.Perm.mul_apply, hinv, hgq]

/-! ## The abelian base group T0 -/

/-- The elations at the base point `0`, as a set of permutations. -/
def E0 : Set Perm21 :=
  Set.range fun k : Fin 15 => elationAt 0 k

/-- The abelian subgroup generated by the elations at `0`. -/
def T0 : Subgroup Perm21 :=
  Subgroup.closure E0

theorem T0_le_L34 : T0 ≤ L34Subgroup := by
  rw [T0, Subgroup.closure_le]
  rintro _ ⟨k, rfl⟩
  exact elation_zero_mem k

/-- `T0` viewed inside `L34`. -/
def TT : Subgroup L34Subgroup :=
  T0.subgroupOf L34Subgroup

theorem elation_zero_mem_T0 (k : Fin 15) : elationAt 0 k ∈ T0 :=
  Subgroup.subset_closure ⟨k, rfl⟩

/-- The elements of `T0` commute pairwise. -/
theorem T0_comm : ∀ a ∈ T0, ∀ b ∈ T0, Commute a b := by
  intro a ha
  refine Subgroup.closure_induction
    (p := fun a _ => ∀ b ∈ T0, Commute a b) ?_ ?_ ?_ ?_ ha
  · rintro _ ⟨k, rfl⟩ b hb
    refine Subgroup.closure_induction
      (p := fun b _ => Commute (elationAt 0 k) b) ?_ ?_ ?_ ?_ hb
    · rintro _ ⟨k', rfl⟩
      exact elation_comm_zero k k'
    · exact Commute.one_right _
    · intro x y _ _ hx hy
      exact hx.mul_right hy
    · intro x _ hx
      exact hx.inv_right
  · intro b _
    exact Commute.one_left _
  · intro x y _ _ hx hy b hb
    exact (hx b hb).mul_left (hy b hb)
  · intro x _ hx b hb
    exact (hx b hb).inv_left

/-! ## Decomposition g = n * t -/

/--
If `N` is normal and transitive, every element of `L34` is a product of an
element of `N` and an element of `TT`.
-/
theorem decompose (N : Subgroup L34Subgroup) (hN : N.Normal)
    (htrans : ∀ u v : Fin 21, ∃ m ∈ N, m.1 u = v) (g : L34Subgroup) :
    ∃ n ∈ N, ∃ t ∈ TT, g = n * t := by
  obtain ⟨gp, hgmem⟩ := g
  refine Subgroup.closure_induction
    (p := fun x hx => ∃ n ∈ N, ∃ t ∈ TT,
      (⟨x, hx⟩ : L34Subgroup) = n * t) ?_ ?_ ?_ ?_ hgmem
  · -- generators: elations, conjugate into T0 by transitivity of N
    intro x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
    have key : ∀ (c : Fin 21) (k : Fin 15) (hxe : x = elationAt c k)
        (hmem : x ∈ L34Subgroup),
        ∃ n ∈ N, ∃ t ∈ TT, (⟨x, hmem⟩ : L34Subgroup) = n * t := by
      intro c k hxe hmem
      obtain ⟨m, hmN, hm0⟩ := htrans 0 c
      have hminv : m.1⁻¹ c = 0 := by
        rw [← hm0, perm_inv_apply_self]
      obtain ⟨k', hk'⟩ := (mapsElations₂_of_mem m.2).2 c k
      rw [inv_inv, hminv] at hk'
      -- t := m⁻¹ * x * m has underlying permutation elationAt 0 k'
      set t : L34Subgroup := m⁻¹ * ⟨x, hmem⟩ * m with htdef
      have htT : t ∈ TT := by
        rw [TT, Subgroup.mem_subgroupOf]
        have : (t : Perm21) = elationAt 0 k' := by
          rw [htdef]
          change m.1⁻¹ * x * m.1 = _
          rw [hxe, ← hk']
        rw [this]
        exact elation_zero_mem_T0 k'
      set n : L34Subgroup := m * t * m⁻¹ * t⁻¹ with hndef
      have hnN : n ∈ N := by
        rw [hndef]
        have h1 : t * m⁻¹ * t⁻¹ ∈ N := by
          have := hN.conj_mem m⁻¹ (N.inv_mem hmN) t
          simpa [mul_assoc] using this
        have := N.mul_mem hmN h1
        simpa [mul_assoc] using this
      refine ⟨n, hnN, t, htT, ?_⟩
      rw [hndef, htdef]
      group
    rcases hx with rfl | rfl | rfl
    · exact key 20 7 l34e1_eq_elation _
    · exact key 18 14 l34e2_eq_elation _
    · exact key 14 5 l34e3_eq_elation _
  · -- identity
    refine ⟨1, N.one_mem, 1, TT.one_mem, ?_⟩
    apply Subtype.ext
    simp
  · -- products
    rintro x y hxm hym ⟨n1, hn1, t1, ht1, hx⟩ ⟨n2, hn2, t2, ht2, hy⟩
    have hxy : (⟨x * y, Subgroup.mul_mem _ hxm hym⟩ : L34Subgroup) =
        (⟨x, hxm⟩ : L34Subgroup) * ⟨y, hym⟩ := rfl
    refine ⟨n1 * (t1 * n2 * t1⁻¹), N.mul_mem hn1 (hN.conj_mem n2 hn2 t1),
      t1 * t2, TT.mul_mem ht1 ht2, ?_⟩
    rw [hxy, hx, hy]
    group
  · -- inverses
    rintro x hxm ⟨n1, hn1, t1, ht1, hx⟩
    have hxi : (⟨x⁻¹, Subgroup.inv_mem _ hxm⟩ : L34Subgroup) =
        (⟨x, hxm⟩ : L34Subgroup)⁻¹ := rfl
    refine ⟨t1⁻¹ * n1⁻¹ * t1, ?_, t1⁻¹, TT.inv_mem ht1, ?_⟩
    · have := hN.conj_mem n1⁻¹ (N.inv_mem hn1) t1⁻¹
      simpa [mul_assoc] using this
    · rw [hxi, hx]
      group

/-! ## Commutators land in N -/

theorem commutator_mem (N : Subgroup L34Subgroup) (hN : N.Normal)
    (htrans : ∀ u v : Fin 21, ∃ m ∈ N, m.1 u = v) (a b : L34Subgroup) :
    ⁅a, b⁆ ∈ N := by
  haveI := hN
  obtain ⟨na, hna, ta, hta, ha⟩ := decompose N hN htrans a
  obtain ⟨nb, hnb, tb, htb, hb⟩ := decompose N hN htrans b
  set φ := QuotientGroup.mk' N with hφ
  have hker : ∀ g : L34Subgroup, φ g = 1 ↔ g ∈ N := by
    intro g
    exact QuotientGroup.eq_one_iff g
  have hφa : φ a = φ ta := by
    rw [ha, map_mul, (hker na).mpr hna, one_mul]
  have hφb : φ b = φ tb := by
    rw [hb, map_mul, (hker nb).mpr hnb, one_mul]
  have hcomm : Commute ta tb := by
    have h := T0_comm ta.1 (Subgroup.mem_subgroupOf.mp hta) tb.1
      (Subgroup.mem_subgroupOf.mp htb)
    exact Subtype.ext h
  have : φ ⁅a, b⁆ = 1 := by
    rw [map_commutatorElement, hφa, hφb, ← map_commutatorElement,
      commutatorElement_eq_one_iff_commute.mpr hcomm, map_one]
  exact (hker _).mp this

/-! ## L34 is perfect -/

theorem gen1_commutator :
    (⟨l34e1, l34e1_mem⟩ : L34Subgroup) =
      ⁅(⟨commU1, commU1_mem⟩ : L34Subgroup), ⟨commV1, commV1_mem⟩⁆ := by
  apply Subtype.ext
  change l34e1 = commU1 * commV1 * commU1⁻¹ * commV1⁻¹
  rw [inv_eq_of_mul_eq_one_right commU1_sq, inv_eq_of_mul_eq_one_right commV1_sq]
  exact l34e1_comm_id

theorem gen2_commutator :
    (⟨l34e2, l34e2_mem⟩ : L34Subgroup) =
      ⁅(⟨commU2, commU2_mem⟩ : L34Subgroup), ⟨commV2, commV2_mem⟩⁆ := by
  apply Subtype.ext
  change l34e2 = commU2 * commV2 * commU2⁻¹ * commV2⁻¹
  rw [inv_eq_of_mul_eq_one_right commU2_sq, inv_eq_of_mul_eq_one_right commV2_sq]
  exact l34e2_comm_id

theorem gen3_commutator :
    (⟨l34e3, l34e3_mem⟩ : L34Subgroup) =
      ⁅(⟨commU3, commU3_mem⟩ : L34Subgroup), ⟨commV3, commV3_mem⟩⁆ := by
  apply Subtype.ext
  change l34e3 = commU3 * commV3 * commU3⁻¹ * commV3⁻¹
  rw [inv_eq_of_mul_eq_one_right commU3_sq, inv_eq_of_mul_eq_one_right commV3_sq]
  exact l34e3_comm_id

/-- `L34` is perfect: every element is a product of commutators. -/
theorem top_le_commutator :
    ∀ g : L34Subgroup, g ∈ ⁅(⊤ : Subgroup L34Subgroup), (⊤ : Subgroup L34Subgroup)⁆ := by
  intro g
  obtain ⟨gp, hgmem⟩ := g
  refine Subgroup.closure_induction
    (p := fun x hx => (⟨x, hx⟩ : L34Subgroup) ∈
      ⁅(⊤ : Subgroup L34Subgroup), (⊤ : Subgroup L34Subgroup)⁆) ?_ ?_ ?_ ?_ hgmem
  · intro x hx
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hx
    rcases hx with rfl | rfl | rfl
    · rw [show (⟨l34e1, _⟩ : L34Subgroup) = ⟨l34e1, l34e1_mem⟩ from rfl,
        gen1_commutator]
      exact Subgroup.commutator_mem_commutator (Subgroup.mem_top _)
        (Subgroup.mem_top _)
    · rw [show (⟨l34e2, _⟩ : L34Subgroup) = ⟨l34e2, l34e2_mem⟩ from rfl,
        gen2_commutator]
      exact Subgroup.commutator_mem_commutator (Subgroup.mem_top _)
        (Subgroup.mem_top _)
    · rw [show (⟨l34e3, _⟩ : L34Subgroup) = ⟨l34e3, l34e3_mem⟩ from rfl,
        gen3_commutator]
      exact Subgroup.commutator_mem_commutator (Subgroup.mem_top _)
        (Subgroup.mem_top _)
  · exact Subgroup.one_mem _
  · intro x y hxm hym hx hy
    exact Subgroup.mul_mem _ hx hy
  · intro x hxm hx
    exact Subgroup.inv_mem _ hx

/-! ## Main theorem -/

set_option maxRecDepth 20000 in
theorem l34e1_ne_one : l34e1 ≠ 1 := by
  intro h
  have h0 : l34e1 (0 : Fin 21) = 0 := by
    rw [h]
    rfl
  exact absurd h0 (by decide)

theorem nontrivial_L34 : Nontrivial L34Subgroup := by
  refine ⟨⟨⟨l34e1, l34e1_mem⟩, 1, ?_⟩⟩
  intro h
  exact l34e1_ne_one (by simpa using congrArg Subtype.val h)

theorem normal_eq_bot_or_eq_top (N : Subgroup L34Subgroup) (hN : N.Normal) :
    N = ⊥ ∨ N = ⊤ := by
  by_cases hbot : N = ⊥
  · exact Or.inl hbot
  right
  obtain ⟨n, hnN, p, hp⟩ := exists_moved_of_ne_bot N hbot
  have htrans : ∀ u v : Fin 21, ∃ m ∈ N, m.1 u = v :=
    fun u v => normal_orbit_witness N hN hnN hp u v
  have hcomm_le : ⁅(⊤ : Subgroup L34Subgroup), (⊤ : Subgroup L34Subgroup)⁆ ≤ N := by
    rw [Subgroup.commutator_le]
    intro g₁ _ g₂ _
    exact commutator_mem N hN htrans g₁ g₂
  refine le_antisymm le_top ?_
  intro g _
  exact hcomm_le (top_le_commutator g)

/-- The concrete `PSL(3,4)` is a simple group. -/
theorem simple_L34 : IsSimpleGroup L34Subgroup :=
  { toNontrivial := nontrivial_L34
    eq_bot_or_eq_top_of_normal := normal_eq_bot_or_eq_top }

end L34
end Sporadic
