/-
Copyright (c) 2026 Kenta.
Authors: Kenta
AI usage: Developed with assistance from Claude Code (Fable 5, 1M context,
high reasoning).
-/
import Mathlib.Algebra.Group.Subgroup.Finite
import Mathlib.GroupTheory.SpecificGroups.Alternating
import FiniteSimpleGroups.Sporadic.M22.Permutations

/-!
# The generated subgroup

This file defines the experimental `M22` as the subgroup of `Equiv.Perm (Fin 22)`
generated by the two explicit permutations in `SporadicM22.Permutations`.
-/

namespace Sporadic

/-- The subgroup generated by the two degree-22 Mathieu generator candidates. -/
def M22Subgroup : Subgroup Perm22 :=
  Subgroup.closure ({m22a, m22b} : Set Perm22)

/-- The experimental Mathieu group `M22`, as a type. -/
abbrev M22 : Type :=
  M22Subgroup

instance instGroupM22 : Group M22 :=
  inferInstance

noncomputable instance instFintypeM22 : Fintype M22 := by
  classical
  infer_instance

/-- The canonical embedding of `M22` into the ambient degree-22 permutation group. -/
abbrev M22.toPerm (g : M22) : Perm22 :=
  g.1

/-- The first generator belongs to the generated subgroup. -/
theorem m22a_mem_M22Subgroup : m22a ∈ M22Subgroup :=
  Subgroup.subset_closure (by simp)

/-- The second generator belongs to the generated subgroup. -/
theorem m22b_mem_M22Subgroup : m22b ∈ M22Subgroup :=
  Subgroup.subset_closure (by simp)

set_option maxRecDepth 40000 in
theorem m22a_mem_alternatingGroup : m22a ∈ alternatingGroup (Fin 22) := by
  rw [Equiv.Perm.mem_alternatingGroup]
  decide

set_option maxRecDepth 40000 in
theorem m22b_mem_alternatingGroup : m22b ∈ alternatingGroup (Fin 22) := by
  rw [Equiv.Perm.mem_alternatingGroup]
  decide

/-- The generated `M22` subgroup lies inside the ambient alternating group. -/
theorem M22Subgroup_le_alternatingGroup : M22Subgroup ≤ alternatingGroup (Fin 22) := by
  rw [M22Subgroup]
  rw [Subgroup.closure_le]
  intro g hg
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hg
  rcases hg with rfl | rfl
  · exact m22a_mem_alternatingGroup
  · exact m22b_mem_alternatingGroup

/-- Every element of the generated `M22` subgroup is an even permutation. -/
theorem M22_toPerm_mem_alternatingGroup (g : M22) : g.1 ∈ alternatingGroup (Fin 22) :=
  M22Subgroup_le_alternatingGroup g.2

/-- Every element of the generated `M22` subgroup has sign one. -/
theorem M22_toPerm_sign (g : M22) : Equiv.Perm.sign g.1 = 1 :=
  Equiv.Perm.mem_alternatingGroup.mp (M22_toPerm_mem_alternatingGroup g)

end Sporadic
